[package]
name = "dynamic-html"
version = "0.1.0"
edition = "2021"
#
# [lib]
# crate-type = ["cdylib"]

[dependencies]
regex = "1.7.1"
pathdiff = "0.2.1"
wasm-bindgen = "=0.2.81"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.94"
